"""length airline

Revision ID: 302f0f5f9d47
Revises: 3d7ab7a079dc
Create Date: 2018-07-02 17:42:20.002292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302f0f5f9d47'
down_revision = '3d7ab7a079dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
