"""initial

Revision ID: 3d7ab7a079dc
Revises: 
Create Date: 2018-07-02 17:32:30.714369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7ab7a079dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport',
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ticket',
    sa.Column('depart_airport_code', sa.String(length=3), nullable=False),
    sa.Column('arrive_airport_code', sa.String(length=3), nullable=False),
    sa.Column('depart_date_time', sa.DateTime(), nullable=False),
    sa.Column('arrive_date_time', sa.DateTime(), nullable=False),
    sa.Column('airline', sa.String(length=10), nullable=False),
    sa.Column('stop_count', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('search_date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('depart_airport_code', 'arrive_airport_code', 'depart_date_time', 'arrive_date_time', 'airline', 'stop_count')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('airport')
    # ### end Alembic commands ###
