"""Added route

Revision ID: 4d1134731c04
Revises: 3d7ab7a079dc
Create Date: 2019-02-21 02:18:25.192987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1134731c04'
down_revision = '3d7ab7a079dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('depart', sa.String(length=10), nullable=False),
    sa.Column('arrive', sa.String(length=10), nullable=False),
    sa.Column('carrier', sa.String(length=10), nullable=False),
    sa.Column('carrier_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('depart', 'arrive', 'carrier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route')
    # ### end Alembic commands ###
