"""added airport name

Revision ID: c910e03a9dc6
Revises: d7bfdde9a01e
Create Date: 2018-06-25 02:37:33.932833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c910e03a9dc6'
down_revision = 'd7bfdde9a01e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('arrive_airport', sa.String(length=30), nullable=True))
    op.add_column('ticket', sa.Column('depart_airport', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'depart_airport')
    op.drop_column('ticket', 'arrive_airport')
    # ### end Alembic commands ###
