"""init

Revision ID: d7bfdde9a01e
Revises: 
Create Date: 2018-06-24 18:28:23.137064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7bfdde9a01e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('depart_airport_code', sa.String(length=5), nullable=False),
    sa.Column('arrive_airport_code', sa.String(length=5), nullable=False),
    sa.Column('depart_date_time', sa.DateTime(), nullable=False),
    sa.Column('arrive_date_time', sa.DateTime(), nullable=True),
    sa.Column('airline', sa.String(length=32), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('stop_count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('depart_airport_code', 'arrive_airport_code', 'depart_date_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    # ### end Alembic commands ###
