"""added search date time

Revision ID: f14c81666c7c
Revises: c910e03a9dc6
Create Date: 2018-06-26 23:51:08.901134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14c81666c7c'
down_revision = 'c910e03a9dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('search_date_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'search_date_time')
    # ### end Alembic commands ###
